apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-backend
  template:
    metadata:
      labels:
        app: my-node-backend
    spec:
      containers:
        - name: my-node-backend
          image: umangrathi110/backend-image:1.0
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi" # Request 256 MB of memory
            limits:
              memory: "512Mi" # Limit to 512 MB of memory
          env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: mongo-url
